#!/bin/bash

# ------------------------------------------------------------------------------
# update revision number

_PWD=$PWD
if ! [ -d src/projects/ams/9.0 ]; then
    echo "src/projects/ams/9.0 - not found"
    exit 1
fi
# generate AMS version information --
cd src/projects/ams/9.0 || exit 1
./UpdateGitVersion activate || exit 1
cd $_PWD

# ------------------------------------------------------------------------------
# update revision number

_PWD=$PWD
if ! [ -d src/projects/abs/4.0 ]; then
    echo "src/projects/abs/4.0 - not found"
    exit 1
fi
# generate ABS version information --
cd src/projects/abs/4.0 || exit 1
./UpdateGitVersion activate || exit 1
VERS="4.`git rev-list --count HEAD`.`git rev-parse --short HEAD`"
cd $_PWD



